import javax.swing.JOptionPane;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

public class AplicaçaoAdm extends javax.swing.JFrame {
    private Compra compra;
    private Administrador adm = new Administrador("admin", "admin", "admin");
    private JanelaAlterar j;
    private Login l;
    private int GerenciadorBotaoCadastro = 0;
    
    //inicializar a aplicação do adm
    public AplicaçaoAdm(JanelaAlterar j) {
        try {
            adm = Arquivo.lerAdm();
            this.j = j;
            this.j.a = this;
            initComponents();
            carregaTabelaProdutos();        //carrega a tabela de produtos
            carregaTabelaCompras();         //carrega a tabela de compras
        } catch (ValorIncoerenteException ex) {
            JOptionPane.showMessageDialog(null, "Valor inválido!", null, HEIGHT);
        }
        
        
    }
    public void attProd(Produto prod) throws ValorIncoerenteException{              //att do produto
        adm.setProdPorCodigo(prod.getCodigo(), prod.getNome(), prod.getMarca(), prod.getPreço(), prod.getQuantidade()); //vai atualizar o produto com as modificações feitas
        carregaTabelaProdutos();        //carregar a tabela de produtos com as modificações feitas
    }
    public void setL(Login l) {
        this.l = l;
    }
    public void setAdm(Administrador administrador) {
        this.adm = administrador;
    }
    
    public void carregaTabelaCompras(){   //responsavel por realizar o preenchimento da tabela de compras
        DefaultTableModel modelo = new DefaultTableModel(new Object[]{"Usuario","Ordem de Compra"},0);
        
        for (Map.Entry<Integer, Compra> set : adm.getEntrySetCompras()) 
        {
            Object linha[] = new Object[]{set.getValue().getUsuario(), set.getValue().getOrdemCompra()};
            modelo.addRow(linha);
        }
        jTable2_compras.setModel(modelo);
        
    }
    
    public void carregaTabelaProdutos(){  //responsavel por realizar o preenchimento da tabela de produtos
        DefaultTableModel modelo = new DefaultTableModel(new Object[]{"codigo","Nome","Quantidade","Marca","Preço"},0);        
        
        for (Map.Entry<Integer, Produto> set : adm.getEntrySetProdutos()) {
            Object linha[] = new Object[]{set.getValue().getCodigo(),
                set.getValue().getNome(),
                set.getValue().getQuantidade(),
                set.getValue().getMarca(),
                set.getValue().getPreço()
                };
            modelo.addRow(linha);
        }
        jTable1_cadastro.setModel(modelo);
        jTable1_cadastro.getColumnModel().getColumn(0).setPreferredWidth(20);
        jTable1_cadastro.getColumnModel().getColumn(1).setPreferredWidth(100);
        jTable1_cadastro.getColumnModel().getColumn(2).setPreferredWidth(50);
        jTable1_cadastro.getColumnModel().getColumn(3).setPreferredWidth(80);
        jTable1_cadastro.getColumnModel().getColumn(4).setPreferredWidth(35);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1_cadastro = new javax.swing.JTable();
        jButton1_cadastro = new javax.swing.JButton();
        jButton2_alterar = new javax.swing.JButton();
        jButton3_apagar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jTextField1_nomeProd = new javax.swing.JTextField();
        jTextField3_quantProd = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField4_marcaProd = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1_preço = new javax.swing.JTextField();
        jButton6_salvar = new javax.swing.JButton();
        jButton7_cancelar = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        textCodigo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2_compras = new javax.swing.JTable();
        jButton4_informaçoes = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1_informaçoes = new javax.swing.JTextArea();
        jButton5_voltar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela do Administrador");

        jTable1_cadastro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Codigo", "Nome", "Quantiade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1_cadastro.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1_cadastro);
        if (jTable1_cadastro.getColumnModel().getColumnCount() > 0) {
            jTable1_cadastro.getColumnModel().getColumn(0).setPreferredWidth(20);
            jTable1_cadastro.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTable1_cadastro.getColumnModel().getColumn(2).setPreferredWidth(20);
        }

        jButton1_cadastro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1_cadastro.setText("Cadastrar Produto");
        jButton1_cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_cadastro_cadastroActionPerformed(evt);
            }
        });

        jButton2_alterar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2_alterar.setText("Alterar Produto");
        jButton2_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_alterarActionPerformed(evt);
            }
        });

        jButton3_apagar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3_apagar.setText("Apagar Produto");
        jButton3_apagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3_apagarActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro"));

        jTextField1_nomeProd.setEditable(false);

        jTextField3_quantProd.setEditable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nome:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Tipo:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Marca:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Quantidade:");

        jTextField4_marcaProd.setEditable(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Preço: ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("R$");

        jTextField1_preço.setEditable(false);
        jTextField1_preço.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_preçoActionPerformed(evt);
            }
        });

        jButton6_salvar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton6_salvar.setText("Salvar"); // NOI18N
        jButton6_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6_salvarActionPerformed(evt);
            }
        });

        jButton7_cancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton7_cancelar.setText("Cancelar"); // NOI18N
        jButton7_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7_cancelarActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo", "Roupas", "Alimentos", "Limpeza" }));
        jComboBox1.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Código:");

        textCodigo.setEditable(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(35, 35, 35)))
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jTextField1_nomeProd)
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton6_salvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton7_cancelar)
                        .addGap(101, 101, 101))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(jTextField1_preço, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textCodigo)
                    .addComponent(jTextField4_marcaProd, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField3_quantProd)))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(452, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1_nomeProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3_quantProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(4, 4, 4)
                .addComponent(jTextField4_marcaProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1_preço, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6_salvar)
                    .addComponent(jButton7_cancelar))
                .addContainerGap())
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(37, 37, 37)
                    .addComponent(jLabel2)
                    .addGap(34, 34, 34)
                    .addComponent(jLabel3)
                    .addContainerGap(91, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3_apagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1_cadastro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2_alterar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(187, 187, 187))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 224, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1_cadastro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2_alterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3_apagar)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Cadastro", jPanel1);

        jTable2_compras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Usuario", "Ordem de compra"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2_compras.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable2_compras);

        jButton4_informaçoes.setText("Informações");
        jButton4_informaçoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4_informaçoesActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Informaçoes"));

        jTextArea1_informaçoes.setEditable(false);
        jTextArea1_informaçoes.setColumns(20);
        jTextArea1_informaçoes.setRows(5);
        jScrollPane3.setViewportView(jTextArea1_informaçoes);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton4_informaçoes)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4_informaçoes)
                .addGap(15, 15, 15))
        );

        jTabbedPane1.addTab("Compras", jPanel2);

        jButton5_voltar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton5_voltar.setText("Voltar");
        jButton5_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5_voltarActionPerformed(evt);
            }
        });

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5_voltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5_voltar)
                    .addComponent(jButton1)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_alterarActionPerformed
        int index = jTable1_cadastro.getSelectedRow();      //pega a linha da tabela
        if(index != -1){
            int aux = (int)jTable1_cadastro.getValueAt(index, 0);       //pega o valor no campo especifico
            j.setProduto(adm.getProdutosCodigo(aux));               //carrega o produto na tabela de alterar o produto
            j.setVisible(true);
            j.mostrarDados(adm.getProdutosCodigo(aux));
            j.codigo = aux;
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um item na tabela", null, HEIGHT);
        }
        
        
    }//GEN-LAST:event_jButton2_alterarActionPerformed

    private void jButton1_cadastro_cadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_cadastro_cadastroActionPerformed
        textCodigo.setEditable(true);
        jTextField1_preço.setEditable(true);
        jTextField1_nomeProd.setEditable(true);
        jComboBox1.setEnabled(true);
        jTextField3_quantProd.setEditable(true);
        jTextField4_marcaProd.setEditable(true);
        GerenciadorBotaoCadastro = 1;
        carregaTabelaProdutos();
    }//GEN-LAST:event_jButton1_cadastro_cadastroActionPerformed

    private void jButton5_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5_voltarActionPerformed
        Arquivo.escreverAdm(adm);
        jTextField1_preço.setEditable(false);
        jTextField1_nomeProd.setEditable(false);
        jComboBox1.setEnabled(false);
        jTextField3_quantProd.setEditable(false);
        jTextField4_marcaProd.setEditable(false);
        GerenciadorBotaoCadastro = 0;
        
        super.setVisible(false);
        l.setVisible(true);
    }//GEN-LAST:event_jButton5_voltarActionPerformed

    private void jTextField1_preçoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_preçoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_preçoActionPerformed

    private void jButton7_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7_cancelarActionPerformed
        jTextField1_preço.setEditable(false);
        jTextField1_nomeProd.setEditable(false);
        jComboBox1.setEnabled(false);
        jTextField3_quantProd.setEditable(false);
        jTextField4_marcaProd.setEditable(false);
        GerenciadorBotaoCadastro = 0;
    }//GEN-LAST:event_jButton7_cancelarActionPerformed

    private void jButton6_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6_salvarActionPerformed
        //salva o produto
        if(jTextField1_nomeProd.getText().equals("")){
            JOptionPane.showMessageDialog(null, "É Obrigatório preencher o campo 'Nome'", null, HEIGHT);
            return;
        }
        else if(jComboBox1.getSelectedItem().toString().equals("Tipo")){
            JOptionPane.showMessageDialog(null, "É Obrigatório preencher o campo 'Tipo'", null, HEIGHT);
            return;
        }
        else if(jTextField3_quantProd.getText().equals("")){
            JOptionPane.showMessageDialog(null, "É Obrigatório preencher o campo 'Quantidade'", null, HEIGHT);
            return;
        }
        else if(jTextField4_marcaProd.getText().equals("")){
            JOptionPane.showMessageDialog(null, "É Obrigatório preencher o campo 'Marca'", null, HEIGHT);
            return;
        }
        else if(jTextField1_preço.getText().equals("")){
            JOptionPane.showMessageDialog(null, "É Obrigatório preencher o campo 'Preço'", null, HEIGHT);
            return;
        }
        try {
            Produto p = new Produto( //cria novo produto
                    jTextField1_nomeProd.getText(),
                    Integer.parseInt(textCodigo.getText()),
                    jComboBox1.getSelectedItem().toString(),
                    Integer.parseInt(jTextField3_quantProd.getText()),
                    Double.parseDouble(jTextField1_preço.getText()),
                    jTextField4_marcaProd.getText()
            );
            if(adm.addProduto(Integer.parseInt(textCodigo.getText()), p)){//adiciona o produto no adm
                JOptionPane.showMessageDialog(null, "Cadastro Realizado Com Sucesso!", null, HEIGHT);
            }else{
                JOptionPane.showMessageDialog(null, "Cadastro não Realizado, código já utilizado!", null, HEIGHT);
            }
        } catch (ValorIncoerenteException ex) {
            JOptionPane.showMessageDialog(null, "Valores inválidos!", null, HEIGHT);
        }
        jTextField1_preço.setEditable(false);
        textCodigo.setEditable(false);
        jTextField1_nomeProd.setEditable(false);
        jComboBox1.setEnabled(false);
        jTextField3_quantProd.setEditable(false);
        jTextField4_marcaProd.setEditable(false);
        textCodigo.setText("");
        jTextField1_preço.setText("");
        jTextField1_nomeProd.setText("");
        jComboBox1.setSelectedIndex(0);
        jTextField3_quantProd.setText("");
        jTextField4_marcaProd.setText("");

        carregaTabelaProdutos();
    }//GEN-LAST:event_jButton6_salvarActionPerformed

    private void jButton3_apagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3_apagarActionPerformed
        int index = jTable1_cadastro.getSelectedRow();//pega linha selecionada
        int aux = (int)jTable1_cadastro.getValueAt(index, 0);//pega codigo da linha
        adm.tiraProduto(aux);//tira o produto
        
        carregaTabelaProdutos();//carrega a tabela

    }//GEN-LAST:event_jButton3_apagarActionPerformed

    private void jButton4_informaçoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4_informaçoesActionPerformed
        String t;
        int index = jTable2_compras.getSelectedRow();//pega a linha 
        int i  = (int)jTable2_compras.getValueAt(index, 1);//pega o codigo
        if(index != -1){
            
//            carregarCompras();
            compra = adm.getCompra(i); //pega a compra com aquele código
            //abaixo é o responsavel por mostrar a compra que foi escolhida
            t = "Usuario: " + compra.getUsuario()+"\n";
            t += "Ordem de Compra: " + compra.getOrdemCompra() + "\n\nProdutos: ";
            
            for (Map.Entry<Produto, Integer> set : compra.getEntrySetCompra()) {
                t += "\nNome: " + set.getKey().getNome();
                t += "\nMarca: " + set.getKey().getMarca();
                t += "\nQuantidade: " + set.getValue();
                t += "\nPreço por unidade: " + set.getKey().getPreço()+ "\n";
            }

            jTextArea1_informaçoes.setText(t);
        }
    }//GEN-LAST:event_jButton4_informaçoesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Arquivo.escreverAdm(adm);//salva as alterações feitas
        JOptionPane.showMessageDialog(null, "Salvo!", null, HEIGHT);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void mainAplicaçaoAdm(JanelaAlterar j) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplicaçaoAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplicaçaoAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplicaçaoAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplicaçaoAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplicaçaoAdm(j).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton1_cadastro;
    private javax.swing.JButton jButton2_alterar;
    private javax.swing.JButton jButton3_apagar;
    private javax.swing.JButton jButton4_informaçoes;
    private javax.swing.JButton jButton5_voltar;
    private javax.swing.JButton jButton6_salvar;
    private javax.swing.JButton jButton7_cancelar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1_cadastro;
    private javax.swing.JTable jTable2_compras;
    private javax.swing.JTextArea jTextArea1_informaçoes;
    private javax.swing.JTextField jTextField1_nomeProd;
    private javax.swing.JTextField jTextField1_preço;
    private javax.swing.JTextField jTextField3_quantProd;
    private javax.swing.JTextField jTextField4_marcaProd;
    private javax.swing.JTextField textCodigo;
    // End of variables declaration//GEN-END:variables
}
