
import static java.awt.image.ImageObserver.HEIGHT;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Aplicaçao extends javax.swing.JFrame {
    private Login l;
    private Administrador administrador;
    private Cliente cliente;
    private Carrinho carrinho = new Carrinho();
    private int indexCliente;
    public Aplicaçao() {
        administrador = new Administrador("admin", "admin", "admin");
        try {
            administrador = Arquivo.lerAdm(); //ler dados do admin
             initComponents();
            carregaTabelaProdutos("Todos");     //carregar tabela de produtos
        } catch (ValorIncoerenteException ex) {
            JOptionPane.showMessageDialog(null, "Valor inválido!", null, HEIGHT);
        }
       
     } 
    public void setL(Login l) {
        this.l = l;
    }
    public void setAdm(Administrador adm) {
        this.administrador = adm;
    }

    public Cliente getCliente() {
        return cliente;
    }
    
    public void setCli(Cliente c) {
        this.cliente = c;
        if (cliente.getCarrinho()!= null){
            tabela_Compras.setModel(cliente.carregaTelaCompraCarrinho());
        }else{
            DefaultTableModel modelo = new DefaultTableModel(new Object[]{"codigo","Nome","Quantidade","Preço"},0);  
        }
    }
    public void setIndexCliente(int i){
        this.indexCliente = i;
    }
    private DefaultTableModel modeloProdutos = new DefaultTableModel(new Object[]{"codigo","Nome","Quantidade","Marca","Preço"},0);
    
    
    public void carregaTabelaProdutos(String tipo){       //metodo responsavel por preencher a tabela com os dados dos produtos
        Object linha[] = new Object[]{0, 
                    "", 
                    0,
                    "",
                    0
                };
        
        modeloProdutos.setRowCount(0);
        for (Map.Entry<Integer, Produto> set : administrador.getEntrySetProdutos()) { //laço responsavel por preencher a tabela usando como base os tipos de produtos
            if(tipo.equals(set.getValue().getTipo())){
                linha = new Object[]{set.getValue().getCodigo(), 
                    set.getValue().getNome(), 
                    set.getValue().getQuantidade(),
                    set.getValue().getMarca(),
                    set.getValue().getPreço()
                };
                modeloProdutos.addRow(linha);
            }
            if(tipo.equals("Todos")){
                linha = new Object[]{
                    set.getValue().getCodigo(), 
                    set.getValue().getNome(), 
                    set.getValue().getQuantidade(),
                    set.getValue().getMarca(),
                    set.getValue().getPreço()
                };
                modeloProdutos.addRow(linha);
            }
        }
        tabela_Produtos.setModel(modeloProdutos);
        tabela_Produtos.getColumnModel().getColumn(0).setPreferredWidth(20);
        tabela_Produtos.getColumnModel().getColumn(1).setPreferredWidth(100);
        tabela_Produtos.getColumnModel().getColumn(2).setPreferredWidth(50);
        tabela_Produtos.getColumnModel().getColumn(3).setPreferredWidth(80);
        tabela_Produtos.getColumnModel().getColumn(4).setPreferredWidth(35);
    }
    
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jButton1_voltar = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_Produtos = new javax.swing.JTable();
        jButton1_buscar = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton2_adicionaCarrinho = new javax.swing.JButton();
        textQuantidade = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela_Compras = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jFormattedTextField1_preçototal = new javax.swing.JFormattedTextField();
        jButton1_comprar = new javax.swing.JButton();
        jButton3_cancelarCompra = new javax.swing.JButton();

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mercado");

        jButton1_voltar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1_voltar.setText("Voltar");
        jButton1_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_voltarActionPerformed(evt);
            }
        });

        tabela_Produtos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nome", "Quantidade", "Marca", "Preço"
            }
        ));
        tabela_Produtos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabela_Produtos);

        jButton1_buscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1_buscar.setText("Buscar");
        jButton1_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_buscarActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Alimentos", "Limpesa", "Roupas" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton2_adicionaCarrinho.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2_adicionaCarrinho.setText("Adicionar no Carrinho");
        jButton2_adicionaCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_adicionaCarrinhoActionPerformed(evt);
            }
        });

        textQuantidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        textQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textQuantidadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2_adicionaCarrinho)
                        .addGap(21, 21, 21))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                        .addComponent(jButton1_buscar)))
                .addGap(75, 75, 75))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2_adicionaCarrinho)
                    .addComponent(textQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1_buscar)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        jTabbedPane1.addTab("Produtos", jPanel1);

        tabela_Compras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Nome", "Quantidade", "Preço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela_Compras.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tabela_Compras);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel1.setText("Preço Total:");

        jFormattedTextField1_preçototal.setEditable(false);
        jFormattedTextField1_preçototal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        //jFormattedTextField1_preçototal.setText("R$ "+cliente.getTotalCarrinho());
        jFormattedTextField1_preçototal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField1_preçototalActionPerformed(evt);
            }
        });

        jButton1_comprar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1_comprar.setText("Comprar");
        jButton1_comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_comprarActionPerformed(evt);
            }
        });

        jButton3_cancelarCompra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3_cancelarCompra.setText("Cancelar");
        jButton3_cancelarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3_cancelarCompraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField1_preçototal)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jButton1_comprar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addComponent(jButton3_cancelarCompra)
                .addGap(75, 75, 75))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField1_preçototal, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1_comprar)
                    .addComponent(jButton3_cancelarCompra))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Carrinho", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1_voltar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1_voltar)
                .addGap(26, 26, 26))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Produtos");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_voltarActionPerformed
        l.attCliente(cliente);
//        l.salvar(administrador);
        tabela_Compras.setModel(cliente.carregaTelaCompraCarrinho());
        jFormattedTextField1_preçototal.setText("R$ "+cliente.getTotalCarrinho());
        super.setVisible(false);
        l.setVisible(true);
    }//GEN-LAST:event_jButton1_voltarActionPerformed

    private void jFormattedTextField1_preçototalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField1_preçototalActionPerformed
        
    }//GEN-LAST:event_jFormattedTextField1_preçototalActionPerformed

    private void jButton1_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_buscarActionPerformed
        carregaTabelaProdutos(jComboBox1.getSelectedItem().toString());
    }//GEN-LAST:event_jButton1_buscarActionPerformed

    private void jButton2_adicionaCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_adicionaCarrinhoActionPerformed
        int index = tabela_Produtos.getSelectedRow(); //responsavel por pegar a linha da tebela que o usuario escolheu
        if (index != -1){                             //caso ele não tenha escolhido nenhuma linha não entra nesse if
            int codigo = (int) modeloProdutos.getValueAt(index, 0); //pega o cogido do produto daquela linha selecionada
            if (textQuantidade.getText().compareTo("") != 0){
                int qtd = Integer.parseInt(textQuantidade.getText());
                if(administrador.verificaQtd(qtd, codigo)){
                    try {                                   //vai ser responsavel por adicionar o item escolhido no carrinho
                        cliente.getCarrinhoCli().addProduto(administrador.getProdutosCodigo(codigo), qtd);
                        tabela_Compras.setModel(cliente.carregaTelaCompraCarrinho());
                        jFormattedTextField1_preçototal.setText("R$ "+cliente.getTotalCarrinho());
                        JOptionPane.showMessageDialog(null, "Produto adicionado ao carrinho.", null, HEIGHT);
                    } catch (ValorIncoerenteException ex) {
                        JOptionPane.showMessageDialog(null, "Valor inválido!", null, HEIGHT);
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Quantidade indisponivel!", null, HEIGHT);
                }
            }else{
                JOptionPane.showMessageDialog(null, "Selecione a quantidade", null, HEIGHT);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um produto!", null, HEIGHT);
        }
    }//GEN-LAST:event_jButton2_adicionaCarrinhoActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton3_cancelarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3_cancelarCompraActionPerformed
        cliente.cancelarCompraCliente();    //vai limpar o carrinho do cliente
        tabela_Compras.setModel(cliente.carregaTelaCompraCarrinho());       //carregar as tabelas
        jFormattedTextField1_preçototal.setText("R$ "+cliente.getTotalCarrinho());
    }//GEN-LAST:event_jButton3_cancelarCompraActionPerformed

    private void jButton1_comprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_comprarActionPerformed
        try {                           //vai realizar a compra
            if(cliente.gerarCompraCarrinho(administrador)){     //verifica as quantidades presentes no carrinho
                Compra compra = new Compra(cliente.getUsuario());       //cria nova compra
                compra.setProdutos(cliente.getCarrinho());              //vai adicionar os produtos no carrinho
                administrador.addCompra(compra.getGeradorOrdem(), compra);      //adiciona a compra no adm                           
                JOptionPane.showMessageDialog(null, "Compra Realizado Com Sucesso!", null, HEIGHT);
                cliente.carrinhoSetNovaQtd();                               
                Arquivo.escreverAdm(administrador);                     //escrever no arquivo o que foi alterado no adm
                
            }else{
                JOptionPane.showMessageDialog(null, "Compra não Realizada", null, HEIGHT);
            }
        } catch (QuantidadeInsuficienteException ex) {
            JOptionPane.showMessageDialog(null, "Quantidade insuficiente.", null, HEIGHT);
        }
        cliente.cancelarCompraCliente();                            //limpar carrinho do cliente
        tabela_Compras.setModel(cliente.carregaTelaCompraCarrinho());
        jFormattedTextField1_preçototal.setText("R$ "+cliente.getTotalCarrinho());
        carregaTabelaProdutos("Todos");
//        Arquivo.
    }//GEN-LAST:event_jButton1_comprarActionPerformed

    private void textQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textQuantidadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void mainAplicaçao() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aplicaçao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aplicaçao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aplicaçao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aplicaçao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aplicaçao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_buscar;
    private javax.swing.JButton jButton1_comprar;
    private javax.swing.JButton jButton1_voltar;
    private javax.swing.JButton jButton2_adicionaCarrinho;
    private javax.swing.JButton jButton3_cancelarCompra;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFormattedTextField jFormattedTextField1_preçototal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tabela_Compras;
    private javax.swing.JTable tabela_Produtos;
    private javax.swing.JFormattedTextField textQuantidade;
    // End of variables declaration//GEN-END:variables

}
