
import java.util.ArrayList;
import javax.swing.JOptionPane;
public class Cadastro extends javax.swing.JFrame {

    private ArrayList<Cliente> clientes = new ArrayList<>();

    public void addUsuario(Cliente u)
    {
        clientes.add(u);
    }
    public void setClientes(ArrayList<Cliente> clientes){
        this.clientes = clientes;
    }
    public ArrayList<Cliente> getUsuario() {
        return clientes;
    }

    public void setUsuario(ArrayList<Cliente> usuario) {
        this.clientes = usuario;
    }
    
    private Login l;

    public void setL(Login l) {
        this.l = l;
    }
    
    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jColorChooser1 = new javax.swing.JColorChooser();
        texto_Nome = new javax.swing.JLabel();
        texto_Usuario = new javax.swing.JLabel();
        texto_Senha = new javax.swing.JLabel();
        c_nome = new javax.swing.JTextField();
        c_usuario = new javax.swing.JTextField();
        c_senha = new javax.swing.JTextField();
        texto_Cadastro = new javax.swing.JLabel();
        botao_Cadastrar = new javax.swing.JButton();
        botao_Cancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela de Cadastro");

        texto_Nome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        texto_Nome.setText("Nome:");

        texto_Usuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        texto_Usuario.setText("Usuario:");

        texto_Senha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        texto_Senha.setText("Senha:");

        c_nome.setToolTipText("Digite seu nome.");
        c_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_nomeActionPerformed(evt);
            }
        });

        c_usuario.setToolTipText("Digite seu nome de usuario.");
        c_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_usuarioActionPerformed(evt);
            }
        });

        c_senha.setToolTipText("Digite sua senha.");

        texto_Cadastro.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        texto_Cadastro.setText("Cadastro");

        botao_Cadastrar.setText("Cadastrar");
        botao_Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_CadastrarActionPerformed(evt);
            }
        });

        botao_Cancelar.setText("Cancelar");
        botao_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_CancelarActionPerformed(evt);
            }
        });

        jLabel1.setText("*");

        jLabel2.setText("*");

        jLabel3.setText("*");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(texto_Nome)
                    .addComponent(texto_Usuario)
                    .addComponent(texto_Senha))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c_senha)
                    .addComponent(c_nome)
                    .addComponent(c_usuario, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(texto_Cadastro)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(botao_Cadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                .addGap(48, 48, 48)
                .addComponent(botao_Cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(texto_Cadastro)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texto_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texto_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texto_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botao_Cadastrar)
                    .addComponent(botao_Cancelar))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void c_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_nomeActionPerformed

    private void c_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_usuarioActionPerformed

    private void botao_CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_CadastrarActionPerformed
        clientes = l.getClientes();//pegar os clintes que já fizeram cadastro para que não seja possivel 2 cadastros com mesmo usuario
        if(c_nome.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "É Obrigatório preencher o campo 'Nome'", null, HEIGHT);
                return;
        }
        else if(c_usuario.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "É Obrigatório preencher o campo 'Usuario'", null, HEIGHT);
                return;
        }
        else if(c_senha.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "É Obrigatório preencher o campo 'Senha'", null, HEIGHT);
                return;
        }
        else{
            boolean flag = false;
            for(int i = 0; i < clientes.size() ; i++){
                if(c_usuario.getText().equals(clientes.get(i).getUsuario())){
                    flag = true;//verifica se tem usuario com mesmo login e att a flag
                }
            }
            if(flag){
                JOptionPane.showMessageDialog(null, "Usuario já escolhido, escolha outro ou realize login", null, HEIGHT);
            }else{
                //se não tiver usuario com aquele username vai adicionar esse novo usuario ao cadastro
                Cliente cliente = new Cliente(c_nome.getText(), c_usuario.getText(), c_senha.getText());
                clientes.add(cliente);
                l.setClientes(clientes);
                super.setVisible(false);
                l.setVisible(true);

                String reset = "";

                c_nome.setText(reset);
                c_usuario.setText(reset);
                c_senha.setText(reset);
            }
            
        }
    }//GEN-LAST:event_botao_CadastrarActionPerformed

    private void botao_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_CancelarActionPerformed
        String reset = "";
                
        c_nome.setText(reset);
        c_usuario.setText(reset);
        c_senha.setText(reset);
        
        super.setVisible(false);
        l.setVisible(true);
    }//GEN-LAST:event_botao_CancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void mainCadastro() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_Cadastrar;
    private javax.swing.JButton botao_Cancelar;
    private javax.swing.JTextField c_nome;
    private javax.swing.JTextField c_senha;
    private javax.swing.JTextField c_usuario;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel texto_Cadastro;
    private javax.swing.JLabel texto_Nome;
    private javax.swing.JLabel texto_Senha;
    private javax.swing.JLabel texto_Usuario;
    // End of variables declaration//GEN-END:variables
}
